[secrets]
aws_access_key_id = "your_aws_access_key_id"
aws_secret_access_key = "your_aws_secret_access_key"
region_name = "us-east-1"
mongo_url = "your_mongo_url"
bucket_name = "project-analytics-output"
sentiment_key = "sentiment/daily_score_copy.json"
topic_key = "topic/2_4_sentiment_topics.json"