[secrets]
aws_access_key_id = "AKIARJIOGROB7MVFOYGX"
aws_secret_access_key = "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"
region_name = "us-east-1"
mongo_url = "mongodb+srv://bda:B1gdata2023@cluster0.igmsvhv.mongodb.net/Tweets?retryWrites=true&w=majority"
bucket_name = "project-analytics-output"
sentiment_key = "sentiment/daily_score_copy.json"
topic_key = "topic/2_4_sentiment_topics.json"